### ISSUE TITLE
Refatoração ADAbot language-processing

### ISSUE THREAD

**Issue by guilhermefgs** [GrupoTuring/ADAbot#13]
Oi gnt, eu estava lendo o código [chatbot.py](https://github.com/turing-usp/ADAbot/blob/main/bot-lib/languageprocessing/chatbot.py) e acho que deveria ser feita uma refatoração. 
Eu abri o código chatbot.py e encontrei a classe QuestionEmbeddings, então acho que deveria começar com essa primeira mudança, por padrão de projeto o nome do arquivo deveria representar o seu conteúdo, nesse caso acho que deveria trocar para question_embeddings.py
Em seguida fui olhar essa classe, e entendo que se estamos usando classes, estamos buscando trabalhar com orientação a objetos. Considerando isso eu acho q a classe QuestionEmbeddings está fazendo mais do que deveria, eu esperaria que esta classe fizesse apenas o embedding de uma question. E portanto, a responsabilidade de responder a questão por similaridade de cossenos deveria estar em outra classe, algo tipo QuestionAnswer, por exemplo. Eu acho q da maneira q tá, fica dificil de ler e compreender o código, por isso acho que deveria ser feita essa refatoração.

**Comment by guilhermefgs** [comment]
A label wontfix é porque não acham importante? Se for porque não tem interessados em resolver esse problema, eu posso resolver.

**Comment by fernandokm** [comment]
> A label wontfix é porque não acham importante? Se for porque não tem interessados em resolver esse problema, eu posso resolver.

To reabrindo então
