### ISSUE TITLE
Problema ao clonar repositório no Windows

### ISSUE THREAD

**Issue by guilhermefgs** [GrupoTuring/ADAbot#14]
Pessoal, alguns meses atrás tentamos ajudar a vick com o problema que agora aconteceu comigo enquanto estava tentando clonar o repositório. 

![image](https://user-images.githubusercontent.com/30242403/120100493-70742300-c117-11eb-90af-3eebd068639e.png)

Encontrei essa discussão https://github.com/desktop/desktop/issues/8694 e acho que o problema pode estar acontecendo porque o repositorio tem um subdiretorio com nome aux, que aparentemente é uma palavra reservada do windows. Minha sugestão é alterar o nome dessa pasta e ver se resolve. 

Mesmo se a causa não for essa, ainda acho que é um problema que precisa ser resolvido para dar acessibilidade para nossos amigos usuários de windows.

**Comment by vitoriars** [comment]
@anor4k @luisaheise

**Comment by anor4k** [comment]
não sabia disso, vou conferir

**Comment by anor4k** [comment]
fiz um refactor na master. acho que o checkout no HEAD não vai ter problema mas provavelmente não vai dar pra dar checkout num commit antigo.
